import type { SalesTeamMember } from "./types";

export const salesTeamMembers: SalesTeamMember[] = [
  {
    id: "sales-01",
    name: "Nguyễn Minh Anh",
    initials: "MA",
    email: "minhanh@ai-nes.edu.vn",
    availability: "active",
    health: "good",
    activeStudents: 46,
    capacity: 60,
    consultedToday: 31,
    admittedThisMonth: 8,
    overdue: 1,
    conversionRate: 17.4,
    regions: ["Cần Thơ"],
    specialties: ["Công nghệ thông tin", "Quản trị kinh doanh"],
    lastActivity: "Đang hoạt động",
  },
  {
    id: "sales-02",
    name: "Trần Ngọc Mai",
    initials: "NM",
    email: "ngocmai@ai-nes.edu.vn",
    availability: "active",
    health: "good",
    activeStudents: 39,
    capacity: 60,
    consultedToday: 26,
    admittedThisMonth: 6,
    overdue: 0,
    conversionRate: 15.4,
    regions: ["Cần Thơ", "Vĩnh Long"],
    specialties: ["Ngôn ngữ Anh", "Quản trị kinh doanh"],
    lastActivity: "Đang hoạt động",
  },
  {
    id: "sales-03",
    name: "Lê Hoàng Nam",
    initials: "HN",
    email: "hoangnam@ai-nes.edu.vn",
    availability: "active",
    health: "support",
    activeStudents: 35,
    capacity: 40,
    consultedToday: 21,
    admittedThisMonth: 4,
    overdue: 3,
    conversionRate: 11.4,
    regions: ["Đồng Tháp"],
    specialties: ["Công nghệ thông tin", "Kế toán"],
    lastActivity: "Đang hoạt động",
    supportReason: "3 hồ sơ chưa được liên hệ đúng hạn",
  },
  {
    id: "sales-04",
    name: "Phạm Gia Hân",
    initials: "GH",
    email: "giahan@ai-nes.edu.vn",
    availability: "active",
    health: "support",
    activeStudents: 31,
    capacity: 40,
    consultedToday: 19,
    admittedThisMonth: 3,
    overdue: 2,
    conversionRate: 9.7,
    regions: ["Cần Thơ"],
    specialties: ["Ngôn ngữ Anh", "Kế toán"],
    lastActivity: "Đang hoạt động",
    supportReason: "Đang gần chạm mức tiếp nhận và còn 2 hồ sơ quá hạn",
  },
  {
    id: "sales-05",
    name: "Võ Thanh Tú",
    initials: "TT",
    email: "thanhtu@ai-nes.edu.vn",
    availability: "active",
    health: "good",
    activeStudents: 22,
    capacity: 40,
    consultedToday: 17,
    admittedThisMonth: 2,
    overdue: 0,
    conversionRate: 9.1,
    regions: ["Vĩnh Long"],
    specialties: ["Quản trị kinh doanh"],
    lastActivity: "Đang hoạt động",
  },
  {
    id: "sales-06",
    name: "Đỗ Anh Quân",
    initials: "AQ",
    email: "anhquan@ai-nes.edu.vn",
    availability: "away",
    health: "good",
    activeStudents: 11,
    capacity: 40,
    consultedToday: 11,
    admittedThisMonth: 1,
    overdue: 0,
    conversionRate: 9.1,
    regions: ["Cần Thơ"],
    specialties: ["Công nghệ thông tin"],
    lastActivity: "Ngoại tuyến · 1 giờ trước",
  },
];
