import type {
  MockAction,
  MockActionType,
  MockRecommendation,
  MockRecommendationRule,
  MockTimingPolicy,
} from "./types";

export const MOCK_ACTION_TYPES: MockActionType[] = [
  {
    code: "CONTACT",
    displayName: "Liên hệ",
    description: "Các hành động tạo kết nối trực tiếp với học sinh hoặc phụ huynh.",
    actionCount: 12,
    sortOrder: 10,
    status: "active",
    modified: "04/09/2026 08:00",
  },
  {
    code: "INFORMATION",
    displayName: "Thông tin",
    description: "Gửi nội dung giúp gia đình hiểu rõ chương trình và lộ trình tuyển sinh.",
    actionCount: 18,
    sortOrder: 20,
    status: "active",
    modified: "03/09/2026 16:20",
  },
  {
    code: "ENGAGEMENT",
    displayName: "Tương tác",
    description: "Mời học sinh tham gia hoạt động để duy trì mức độ quan tâm.",
    actionCount: 9,
    sortOrder: 30,
    status: "active",
    modified: "02/09/2026 14:10",
  },
  {
    code: "APPLICATION",
    displayName: "Hồ sơ đăng ký",
    description: "Theo dõi các bước hoàn thiện hồ sơ và thủ tục dự tuyển.",
    actionCount: 14,
    sortOrder: 40,
    status: "active",
    modified: "01/09/2026 10:45",
  },
  {
    code: "CONVERSION",
    displayName: "Chuyển đổi",
    description: "Hỗ trợ các bước từ quan tâm đến xác nhận nhập học.",
    actionCount: 8,
    sortOrder: 50,
    status: "active",
    modified: "30/08/2026 09:15",
  },
  {
    code: "PARENT",
    displayName: "Phụ huynh",
    description: "Các hành động dành riêng cho người ra quyết định trong gia đình.",
    actionCount: 7,
    sortOrder: 60,
    status: "active",
    modified: "28/08/2026 11:30",
  },
  {
    code: "RECOVERY",
    displayName: "Khôi phục",
    description: "Kết nối lại với hồ sơ đã im lặng hoặc có nguy cơ rời phễu.",
    actionCount: 6,
    sortOrder: 70,
    status: "active",
    modified: "27/08/2026 15:50",
  },
  {
    code: "INTERNAL",
    displayName: "Nội bộ",
    description: "Việc cần làm trong nội bộ đội ngũ tuyển sinh.",
    actionCount: 5,
    sortOrder: 80,
    status: "active",
    modified: "25/08/2026 13:00",
  },
];

export const MOCK_ACTIONS: MockAction[] = [
  {
    code: "CALL",
    displayName: "Gọi tư vấn",
    description: "Gọi để xác nhận nhu cầu và thống nhất bước tiếp theo.",
    actionType: "CONTACT",
    channel: "CALL",
    executionType: "MANUAL",
    allowedActors: ["Sale", "Lead Sales"],
    allowedTimeSlots: ["6-12", "12-18"],
    requiresApproval: false,
    aiAllowed: true,
    enabled: true,
    modified: "04/09/2026 08:00",
  },
  {
    code: "SEND_EMAIL",
    displayName: "Gửi email tư vấn",
    description: "Gửi thông tin phù hợp với mối quan tâm hiện tại của học sinh.",
    actionType: "INFORMATION",
    channel: "EMAIL",
    executionType: "AI_ASSISTED",
    allowedActors: ["Sale", "Marketing"],
    allowedTimeSlots: [],
    requiresApproval: true,
    aiAllowed: true,
    enabled: true,
    modified: "03/09/2026 16:20",
  },
  {
    code: "SEND_ZALO",
    displayName: "Gửi Zalo",
    description: "Gửi tin nhắn ngắn để nhắc lại thông tin cần thiết.",
    actionType: "CONTACT",
    channel: "MESSAGE",
    executionType: "MANUAL",
    allowedActors: ["Sale", "Lead Sales", "Promoter"],
    allowedTimeSlots: ["6-12", "12-18"],
    requiresApproval: false,
    aiAllowed: true,
    enabled: true,
    modified: "03/09/2026 11:05",
  },
  {
    code: "SEND_SMS",
    displayName: "Gửi SMS",
    description: "Gửi nhắc hẹn hoặc thông tin ngắn qua SMS.",
    actionType: "INFORMATION",
    channel: "MESSAGE",
    executionType: "MANUAL",
    allowedActors: ["Marketing", "Sale"],
    allowedTimeSlots: [],
    requiresApproval: false,
    aiAllowed: false,
    enabled: true,
    modified: "02/09/2026 09:40",
  },
  {
    code: "INVITE_CAMPUS_TOUR",
    displayName: "Mời tham quan cơ sở",
    description: "Mời học sinh và phụ huynh đến trải nghiệm môi trường học tập.",
    actionType: "ENGAGEMENT",
    channel: "CALL",
    executionType: "MANUAL",
    allowedActors: ["Promoter", "Sale"],
    allowedTimeSlots: ["6-12", "12-18"],
    requiresApproval: false,
    aiAllowed: true,
    enabled: true,
    modified: "01/09/2026 17:10",
  },
  {
    code: "REQUEST_DOCUMENTS",
    displayName: "Nhắc bổ sung hồ sơ",
    description: "Nhắc học sinh hoàn thiện giấy tờ còn thiếu trong hồ sơ dự tuyển.",
    actionType: "APPLICATION",
    channel: "MESSAGE",
    executionType: "AI_ASSISTED",
    allowedActors: ["Sale", "Admissions Director"],
    allowedTimeSlots: [],
    requiresApproval: true,
    aiAllowed: true,
    enabled: true,
    modified: "31/08/2026 15:35",
  },
  {
    code: "CONFIRM_ENROLLMENT",
    displayName: "Xác nhận nhập học",
    description: "Liên hệ để xác nhận quyết định và hỗ trợ bước nhập học.",
    actionType: "CONVERSION",
    channel: "CALL",
    executionType: "MANUAL",
    allowedActors: ["Lead Sales", "Admissions Director"],
    allowedTimeSlots: ["6-12", "12-18"],
    requiresApproval: false,
    aiAllowed: true,
    enabled: true,
    modified: "30/08/2026 09:15",
  },
  {
    code: "CREATE_FOLLOW_UP",
    displayName: "Tạo việc theo dõi",
    description: "Tạo việc tiếp theo và giao cho người phụ trách hồ sơ.",
    actionType: "INTERNAL",
    channel: "NONE",
    executionType: "AI_ASSISTED",
    allowedActors: ["Sale", "Lead Sales", "Promoter"],
    allowedTimeSlots: [],
    requiresApproval: false,
    aiAllowed: true,
    enabled: true,
    modified: "29/08/2026 14:25",
  },
  {
    code: "REACTIVATE_LEAD",
    displayName: "Kết nối lại hồ sơ",
    description: "Gợi ý cách mở lại cuộc trò chuyện với hồ sơ đã im lặng.",
    actionType: "RECOVERY",
    channel: "MESSAGE",
    executionType: "AI_ASSISTED",
    allowedActors: ["Sale", "Lead Sales"],
    allowedTimeSlots: [],
    requiresApproval: true,
    aiAllowed: true,
    enabled: false,
    modified: "27/08/2026 15:50",
  },
];

export const MOCK_TIMING_POLICIES: MockTimingPolicy[] = [
  {
    policyKey: "FOLLOW_UP_24H",
    displayName: "Theo dõi trong 24 giờ",
    triggerType: "event",
    triggerLabel: "Sau sự kiện",
    timing: "+24 giờ sau khi tạo",
    timeSlot: "6:00 – 18:00",
    recurrence: "Không lặp",
    status: "active",
    usedBy: 4,
  },
  {
    policyKey: "SAME_DAY_CONTACT",
    displayName: "Liên hệ trong ngày",
    triggerType: "relative",
    triggerLabel: "Theo thời gian tương đối",
    timing: "Trong ngày phát sinh",
    timeSlot: "8:00 – 18:00",
    recurrence: "Không lặp",
    status: "active",
    usedBy: 7,
  },
  {
    policyKey: "APPLICATION_DEADLINE",
    displayName: "Trước hạn nộp hồ sơ",
    triggerType: "deadline",
    triggerLabel: "Trước hạn",
    timing: "48 giờ trước hạn hồ sơ",
    timeSlot: "8:00 – 20:00",
    recurrence: "Không lặp",
    status: "active",
    usedBy: 3,
  },
  {
    policyKey: "WEEKLY_REENGAGEMENT",
    displayName: "Theo dõi lại hàng tuần",
    triggerType: "schedule",
    triggerLabel: "Theo lịch",
    timing: "Mỗi 7 ngày",
    timeSlot: "9:00 – 17:00",
    recurrence: "Hàng tuần",
    status: "inactive",
    usedBy: 2,
  },
];

export const MOCK_RECOMMENDATION_RULES: MockRecommendationRule[] = [
  {
    ruleKey: "unaddressed_intent",
    displayName: "Xử lý nhu cầu chưa được phản hồi",
    description: "Gợi ý liên hệ khi nhu cầu mới chưa có hoạt động phù hợp.",
    status: "published",
    enabled: true,
    version: 3,
    actionCode: "CALL",
    actionLabel: "Gọi tư vấn",
    priority: "high",
    triggerType: "event",
    triggerLabel: "Khi có nhu cầu mới",
    timingPolicy: "Theo dõi trong 24 giờ",
    conditions: [
      { field: "student.lifecycle_stage", label: "Giai đoạn hồ sơ", operator: "là một trong", value: "Mới · Đã liên hệ" },
      { field: "intent.last_activity_at", label: "Hoạt động gần nhất", operator: "trống", value: "" },
    ],
    cooldown: "3 ngày",
    maxOccurrences: 1,
    expiresAfter: "72 giờ",
    modified: "04/09/2026 08:00",
  },
  {
    ruleKey: "application_document_gap",
    displayName: "Nhắc hoàn thiện hồ sơ",
    description: "Gợi ý nhắc khi hồ sơ còn thiếu giấy tờ gần đến hạn nộp.",
    status: "draft",
    enabled: false,
    version: 1,
    actionCode: "REQUEST_DOCUMENTS",
    actionLabel: "Nhắc bổ sung hồ sơ",
    priority: "high",
    triggerType: "deadline",
    triggerLabel: "Trước hạn nộp hồ sơ",
    timingPolicy: "Trước hạn nộp hồ sơ",
    conditions: [
      { field: "application.missing_document_count", label: "Số giấy tờ còn thiếu", operator: "lớn hơn", value: "0" },
      { field: "application.deadline", label: "Hạn nộp hồ sơ", operator: "trong vòng", value: "48 giờ" },
    ],
    cooldown: "1 ngày",
    maxOccurrences: 2,
    expiresAfter: "48 giờ",
    modified: "03/09/2026 16:20",
  },
  {
    ruleKey: "campus_tour_follow_up",
    displayName: "Theo dõi sau tham quan",
    description: "Gợi ý liên hệ sau khi học sinh đã tham quan cơ sở.",
    status: "published",
    enabled: true,
    version: 2,
    actionCode: "CALL",
    actionLabel: "Gọi tư vấn",
    priority: "medium",
    triggerType: "event",
    triggerLabel: "Sau hoạt động tham quan",
    timingPolicy: "Liên hệ trong ngày",
    conditions: [
      { field: "activity.type", label: "Loại hoạt động", operator: "là", value: "Tham quan cơ sở" },
    ],
    cooldown: "14 ngày",
    maxOccurrences: 1,
    expiresAfter: "7 ngày",
    modified: "01/09/2026 17:10",
  },
  {
    ruleKey: "lead_cooling_down",
    displayName: "Kết nối lại hồ sơ ít tương tác",
    description: "Gợi ý mở lại cuộc trò chuyện khi mức độ quan tâm giảm.",
    status: "published",
    enabled: true,
    version: 4,
    actionCode: "REACTIVATE_LEAD",
    actionLabel: "Kết nối lại hồ sơ",
    priority: "medium",
    triggerType: "relative",
    triggerLabel: "Sau thời gian không tương tác",
    timingPolicy: "Theo dõi lại hàng tuần",
    conditions: [
      { field: "student.last_activity_at", label: "Hoạt động gần nhất", operator: "quá", value: "14 ngày" },
      { field: "student.lifecycle_stage", label: "Giai đoạn hồ sơ", operator: "không phải là", value: "Đã mất" },
    ],
    cooldown: "30 ngày",
    maxOccurrences: 2,
    expiresAfter: "30 ngày",
    modified: "30/08/2026 09:15",
  },
];

export const MOCK_RECOMMENDATIONS: MockRecommendation[] = [
  {
    id: "REC-2026-0841",
    studentName: "Nguyễn Minh Anh",
    studentCode: "HS-2026-0148",
    lifecycleStage: "Đã liên hệ",
    ruleKey: "unaddressed_intent",
    ruleLabel: "Nhu cầu chưa được phản hồi",
    actionLabel: "Gọi tư vấn",
    channel: "CALL",
    priority: "high",
    status: "new",
    confidence: 92,
    expectedImpact: "Xác nhận nhu cầu",
    expiresAt: "Hôm nay, 18:00",
    createdAt: "10 phút trước",
  },
  {
    id: "REC-2026-0838",
    studentName: "Trần Gia Huy",
    studentCode: "HS-2026-0206",
    lifecycleStage: "Đang cân nhắc",
    ruleKey: "application_document_gap",
    ruleLabel: "Hồ sơ còn thiếu giấy tờ",
    actionLabel: "Nhắc bổ sung hồ sơ",
    channel: "MESSAGE",
    priority: "high",
    status: "acknowledged",
    confidence: 86,
    expectedImpact: "Giảm hồ sơ trễ hạn",
    expiresAt: "Ngày mai, 12:00",
    createdAt: "35 phút trước",
  },
  {
    id: "REC-2026-0831",
    studentName: "Lê Khánh Linh",
    studentCode: "HS-2026-0102",
    lifecycleStage: "Đã tham quan",
    ruleKey: "campus_tour_follow_up",
    ruleLabel: "Theo dõi sau tham quan",
    actionLabel: "Gọi tư vấn",
    channel: "CALL",
    priority: "medium",
    status: "new",
    confidence: 79,
    expectedImpact: "Duy trì quan tâm",
    expiresAt: "04/09/2026, 17:00",
    createdAt: "1 giờ trước",
  },
  {
    id: "REC-2026-0822",
    studentName: "Phạm Đức Long",
    studentCode: "HS-2026-0187",
    lifecycleStage: "Đang tư vấn",
    ruleKey: "lead_cooling_down",
    ruleLabel: "Hồ sơ ít tương tác",
    actionLabel: "Kết nối lại hồ sơ",
    channel: "MESSAGE",
    priority: "medium",
    status: "deferred",
    confidence: 73,
    expectedImpact: "Mở lại trao đổi",
    expiresAt: "06/09/2026, 17:00",
    createdAt: "Hôm qua, 16:20",
  },
];
