import type {
  ActivityPoint,
  AiInsight,
  AttentionItem,
  AdmissionsTrendPoint,
  CampusPerformancePoint,
  DirectorKpi,
  ExecutiveAction,
  ForecastPoint,
  MarketOverviewItem,
  PipelineStage,
  SourcePerformance,
  TeamPerformance,
} from "./types";

export const directorKpis: DirectorKpi[] = [
  {
    id: "prospects",
    label: "Tổng hồ sơ tiềm năng",
    value: "24,860",
    target: "30,000",
    achievement: "82.9%",
    change: "+9.8%",
    helper: "so với kỳ trước",
    tone: "primary",
  },
  {
    id: "qualified",
    label: "Hồ sơ đủ điều kiện",
    value: "14,420",
    target: "18,000",
    achievement: "80.1%",
    change: "+12.4%",
    helper: "so với tuần trước",
    tone: "info",
  },
  {
    id: "applicants",
    label: "Đã nộp hồ sơ",
    value: "6,980",
    target: "8,200",
    achievement: "85.1%",
    change: "+8.6%",
    helper: "so với kỳ trước",
    tone: "warning",
  },
  {
    id: "accepted",
    label: "Đã trúng tuyển",
    value: "4,820",
    target: "6,000",
    achievement: "80.3%",
    change: "+10.1%",
    helper: "so với kỳ trước",
    tone: "info",
  },
  {
    id: "enrollment",
    label: "Đã nhập học",
    value: "3,820",
    target: "5,000",
    achievement: "76.4%",
    change: "+6.8%",
    helper: "so với kỳ trước",
    tone: "success",
  },
  {
    id: "conversion-rate",
    label: "Tỷ lệ chuyển đổi",
    value: "15.4%",
    target: "18.0%",
    achievement: "85.6%",
    change: "+1.2%",
    helper: "so với cùng kỳ",
    tone: "success",
  },
  {
    id: "expected-enrollment",
    label: "Dự báo nhập học",
    value: "4,680",
    target: "5,000",
    achievement: "93.6%",
    change: "+14.2%",
    helper: "độ tin cậy 72%",
    tone: "primary",
  },
  {
    id: "expected-revenue",
    label: "Dự báo doanh thu",
    value: "468B",
    target: "520B",
    achievement: "90.0%",
    change: "+11.5%",
    helper: "theo xu hướng hiện tại",
    tone: "warning",
  },
  {
    id: "actual-revenue",
    label: "Doanh thu thực tế",
    value: "382B",
    target: "520B",
    achievement: "73.5%",
    change: "+8.1%",
    helper: "từ hồ sơ đã nhập học",
    tone: "info",
  },
  {
    id: "target-achievement",
    label: "Mức đạt chỉ tiêu",
    value: "76.4%",
    target: "100%",
    achievement: "76.4%",
    change: "+4.3%",
    helper: "mục tiêu niên khóa 2026",
    tone: "danger",
  },
];

export const admissionsPipeline: PipelineStage[] = [
  {
    id: "prospect",
    label: "Hồ sơ tiềm năng",
    value: "24,860",
    percentage: 100,
    conversion: "100%",
    barClassName: "bg-brand-500",
  },
  {
    id: "engaged",
    label: "Đã tương tác",
    value: "18,840",
    percentage: 76,
    conversion: "75.8%",
    barClassName: "bg-primary-300",
  },
  {
    id: "qualified",
    label: "Đủ điều kiện",
    value: "14,420",
    percentage: 58,
    conversion: "76.5%",
    barClassName: "bg-blue-400",
  },
  {
    id: "counselling",
    label: "Đang tư vấn",
    value: "10,240",
    percentage: 41,
    conversion: "71.0%",
    barClassName: "bg-purple-400",
  },
  {
    id: "application",
    label: "Đã nộp hồ sơ",
    value: "6,980",
    percentage: 28,
    conversion: "68.2%",
    barClassName: "bg-orange-400",
  },
  {
    id: "accepted",
    label: "Đã trúng tuyển",
    value: "4,820",
    percentage: 19,
    conversion: "69.1%",
    barClassName: "bg-cyan-500",
  },
  {
    id: "enrolled",
    label: "Đã nhập học",
    value: "3,820",
    percentage: 15,
    conversion: "79.3%",
    barClassName: "bg-green-500",
  },
];

export const marketOverview: MarketOverviewItem[] = [
  {
    id: "southeast",
    name: "Đông Nam Bộ",
    prospects: "8,420",
    enrolled: "1,286",
    conversion: "15.3%",
    growth: "+18.4%",
    coverage: 86,
    tone: "primary",
  },
  {
    id: "red-river",
    name: "Đồng bằng sông Hồng",
    prospects: "6,980",
    enrolled: "1,108",
    conversion: "15.9%",
    growth: "+12.2%",
    coverage: 78,
    tone: "info",
  },
  {
    id: "mekong",
    name: "Đồng bằng sông Cửu Long",
    prospects: "4,860",
    enrolled: "612",
    conversion: "12.6%",
    growth: "-8.2%",
    coverage: 62,
    tone: "danger",
  },
  {
    id: "central",
    name: "Bắc & Nam Trung Bộ",
    prospects: "4,600",
    enrolled: "814",
    conversion: "17.7%",
    growth: "+21.6%",
    coverage: 71,
    tone: "success",
  },
];

export const aiInsights: AiInsight[] = [
  {
    id: "dong-nai-risk",
    type: "risk",
    title: "Chuyển đổi tại Đồng Nai giảm 14%",
    description: "Tỷ lệ từ nộp hồ sơ đến nhập học giảm liên tục trong 14 ngày gần đây.",
    evidence: "4 trường có quy mô lớn chưa có hoạt động tuyển sinh mới.",
    metric: "-14%",
    href: "/director/regional-performance",
  },
  {
    id: "can-tho-opportunity",
    type: "opportunity",
    title: "Cần Thơ còn dư địa khai thác lớn",
    description: "12 trường THPT có hơn 8.000 học sinh lớp 12 nhưng penetration còn thấp.",
    evidence: "Độ phủ hiện tại chỉ đạt 42% so với tiềm năng thị trường.",
    metric: "94/100",
    href: "/director/market-intelligence",
  },
  {
    id: "revenue-opportunity",
    type: "revenue",
    title: "Cơ hội tăng thêm 12,4B doanh thu",
    description: "Chỉ cần tăng conversion nhóm trường tiềm năng thêm 3%.",
    evidence: "Nhóm này đang có 1.240 hồ sơ đủ điều kiện chưa được chăm sóc đủ.",
    metric: "+12.4B",
    href: "/director/revenue-forecast",
  },
];

export const executiveActions: ExecutiveAction[] = [
  {
    id: "increase-coverage",
    title: "Tăng độ phủ đội ngũ tại Cần Thơ",
    description: "Phân bổ thêm 2 nhân sự cho cụm trường có điểm cơ hội cao.",
    impact: "+80 dự báo nhập học",
    href: "/director/ai/next-best-action",
  },
  {
    id: "school-event",
    title: "Tổ chức sự kiện tại Đồng Nai",
    description: "Kích hoạt tư vấn hướng nghiệp cho 4 trường chưa có hoạt động trong 45 ngày.",
    impact: "+3.0% chuyển đổi",
    href: "/director/schools",
  },
  {
    id: "reengage-qualified",
    title: "Chăm sóc lại nhóm hồ sơ đủ điều kiện",
    description: "Ưu tiên 1.240 hồ sơ có điểm tiềm năng cao nhưng chưa có tương tác mới.",
    impact: "+12.4B doanh thu",
    href: "/director/ai/next-best-action",
  },
];

export const attentionItems: AttentionItem[] = [
  {
    id: "sla-breached",
    label: "SLA đã vi phạm",
    description: "Cần trưởng nhóm xử lý và ghi nhận lý do",
    count: "24 hồ sơ",
    priority: "high",
    tone: "danger",
    href: "/director/sla",
  },
  {
    id: "unassigned",
    label: "Chưa phân công",
    description: "Đang chờ phân công theo cơ sở và ngành",
    count: "68 hồ sơ",
    priority: "high",
    tone: "warning",
    href: "/director/students",
  },
  {
    id: "intake-review",
    label: "Hồ sơ chờ rà soát",
    description: "Nghi vấn trùng danh tính hoặc thiếu dữ liệu",
    count: "17 hồ sơ",
    priority: "medium",
    tone: "info",
    href: "/director/students",
  },
  {
    id: "conversion",
    label: "Chờ đối soát chuyển đổi",
    description: "Hồ sơ đã nhập học chưa liên kết hoàn tất",
    count: "9 hồ sơ",
    priority: "medium",
    tone: "primary",
    href: "/director/admission-funnel",
  },
  {
    id: "approvals",
    label: "Phê duyệt đang chờ",
    description: "Thay đổi danh mục học thuật và chính sách",
    count: "7 yêu cầu",
    priority: "low",
    tone: "success",
    href: "/director/ai/next-best-action",
  },
];

export const teamPerformance: TeamPerformance[] = [
  {
    id: "hanoi-tech",
    name: "Hà Nội · Khối Công nghệ",
    campus: "HN",
    activeLeads: "2,846",
    sla: "96.4%",
    enrolled: "286",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "hcm-business",
    name: "TP.HCM · Khối Kinh tế",
    campus: "HCM",
    activeLeads: "2,418",
    sla: "94.1%",
    enrolled: "241",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "danang-language",
    name: "Đà Nẵng · Khối Ngôn ngữ",
    campus: "ĐN",
    activeLeads: "1,764",
    sla: "91.8%",
    enrolled: "176",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "hotline-national",
    name: "Hotline toàn quốc",
    campus: "ALL",
    activeLeads: "3,112",
    sla: "88.6%",
    enrolled: "155",
    conversion: "5.0%",
    trend: "down",
  },
];

export const sourcePerformance: SourcePerformance[] = [
  {
    id: "facebook",
    label: "Quảng cáo Facebook",
    leads: "3,920",
    applicants: "684",
    enrolled: "318",
    share: 31,
    barClassName: "bg-brand-500",
    chartColor: "var(--brand-500)",
  },
  {
    id: "school-tour",
    label: "Tư vấn tại trường",
    leads: "2,486",
    applicants: "524",
    enrolled: "286",
    share: 24,
    barClassName: "bg-orange-400",
    chartColor: "var(--warning-500)",
  },
  {
    id: "zalo",
    label: "Zalo OA",
    leads: "2,138",
    applicants: "418",
    enrolled: "224",
    share: 19,
    barClassName: "bg-cyan-500",
    chartColor: "var(--info-500)",
  },
  {
    id: "website",
    label: "Website / Biểu mẫu",
    leads: "1,842",
    applicants: "326",
    enrolled: "121",
    share: 14,
    barClassName: "bg-purple-400",
    chartColor: "var(--primary-300)",
  },
  {
    id: "open-day",
    label: "Ngày hội tuyển sinh",
    leads: "1,026",
    applicants: "232",
    enrolled: "77",
    share: 8,
    barClassName: "bg-green-500",
    chartColor: "var(--success-500)",
  },
];

export const admissionsTrend: Record<string, AdmissionsTrendPoint[]> = {
  "7d": [
    { label: "T2", newLeads: 310, applicants: 112, enrolled: 42 },
    { label: "T3", newLeads: 362, applicants: 128, enrolled: 48 },
    { label: "T4", newLeads: 348, applicants: 121, enrolled: 51 },
    { label: "T5", newLeads: 401, applicants: 146, enrolled: 58 },
    { label: "T6", newLeads: 386, applicants: 138, enrolled: 55 },
    { label: "T7", newLeads: 434, applicants: 159, enrolled: 62 },
    { label: "CN", newLeads: 486, applicants: 176, enrolled: 68 },
  ],
  "30d": [
    { label: "Tuần 1", newLeads: 1220, applicants: 438, enrolled: 174 },
    { label: "Tuần 2", newLeads: 1480, applicants: 512, enrolled: 208 },
    { label: "Tuần 3", newLeads: 1694, applicants: 628, enrolled: 256 },
    { label: "Tuần 4", newLeads: 1852, applicants: 706, enrolled: 288 },
  ],
  year: [
    { label: "T1", newLeads: 12400, applicants: 2900, enrolled: 1240 },
    { label: "T2", newLeads: 13840, applicants: 3420, enrolled: 1540 },
    { label: "T3", newLeads: 15120, applicants: 4010, enrolled: 1830 },
    { label: "T4", newLeads: 16680, applicants: 4560, enrolled: 2190 },
    { label: "T5", newLeads: 18320, applicants: 5120, enrolled: 2610 },
    { label: "T6", newLeads: 20140, applicants: 5740, enrolled: 3020 },
    { label: "T7", newLeads: 22580, applicants: 6320, enrolled: 3440 },
    { label: "T8", newLeads: 24860, applicants: 6980, enrolled: 3820 },
  ],
};

export const enrollmentForecast: ForecastPoint[] = [
  { label: "T1", actual: 420, forecast: 420, target: 520 },
  { label: "T2", actual: 860, forecast: 860, target: 1_020 },
  { label: "T3", actual: 1_320, forecast: 1_320, target: 1_560 },
  { label: "T4", actual: 1_860, forecast: 1_860, target: 2_120 },
  { label: "T5", actual: 2_410, forecast: 2_410, target: 2_700 },
  { label: "T6", actual: 2_920, forecast: 2_920, target: 3_280 },
  { label: "T7", actual: 3_420, forecast: 3_420, target: 3_920 },
  { label: "T8", actual: 3_820, forecast: 3_820, target: 4_180 },
  { label: "T9", actual: null, forecast: 4_180, target: 4_560 },
  { label: "T10", actual: null, forecast: 4_680, target: 5_000 },
];

export const campusPerformanceChart: CampusPerformancePoint[] = [
  { name: "Đông Nam Bộ", activeRecords: 8420, applicants: 2384, enrolled: 1286 },
  { name: "Đồng bằng sông Hồng", activeRecords: 6980, applicants: 2146, enrolled: 1108 },
  { name: "Đồng bằng sông Cửu Long", activeRecords: 4860, applicants: 1280, enrolled: 612 },
  { name: "Bắc & Nam Trung Bộ", activeRecords: 4600, applicants: 1170, enrolled: 814 },
];

export const weeklyActivity: ActivityPoint[] = [
  { label: "T2", interactions: 680, sla: 94 },
  { label: "T3", interactions: 742, sla: 92 },
  { label: "T4", interactions: 816, sla: 95 },
  { label: "T5", interactions: 904, sla: 91 },
  { label: "T6", interactions: 862, sla: 93 },
  { label: "T7", interactions: 724, sla: 96 },
  { label: "CN", interactions: 512, sla: 98 },
];
