import type {
  AttentionItem,
  DirectorKpi,
  PipelineStage,
  SourcePerformance,
  TeamPerformance,
} from "./types";

export const directorKpis: DirectorKpi[] = [
  {
    id: "active-students",
    label: "Hồ sơ đang hoạt động",
    value: "12,846",
    change: "+8.4%",
    helper: "so với kỳ trước",
    tone: "primary",
  },
  {
    id: "new-leads",
    label: "Hồ sơ mới hôm nay",
    value: "486",
    change: "+12.6%",
    helper: "so với hôm qua",
    tone: "info",
  },
  {
    id: "sla",
    label: "SLA đạt chuẩn",
    value: "92.8%",
    change: "+3.2%",
    helper: "mục tiêu 90%",
    tone: "success",
  },
  {
    id: "applicants",
    label: "Đã nộp hồ sơ",
    value: "2,184",
    change: "+18.1%",
    helper: "trong niên khóa 2026",
    tone: "warning",
  },
  {
    id: "enrolled",
    label: "Đã nhập học",
    value: "1,026",
    change: "+14.7%",
    helper: "tỷ lệ 7.9% trên active",
    tone: "success",
  },
];

export const admissionsPipeline: PipelineStage[] = [
  {
    id: "lead",
    label: "Hồ sơ mới",
    value: "12,846",
    percentage: 100,
    conversion: "100%",
    barClassName: "bg-brand-500",
  },
  {
    id: "mql",
    label: "Hồ sơ tiềm năng",
    value: "8,964",
    percentage: 70,
    conversion: "69.8%",
    barClassName: "bg-purple-400",
  },
  {
    id: "sql",
    label: "Đủ điều kiện",
    value: "5,486",
    percentage: 52,
    conversion: "61.2%",
    barClassName: "bg-blue-400",
  },
  {
    id: "applicant",
    label: "Đã nộp hồ sơ",
    value: "2,184",
    percentage: 36,
    conversion: "39.8%",
    barClassName: "bg-orange-400",
  },
  {
    id: "admitted",
    label: "Đã trúng tuyển",
    value: "1,482",
    percentage: 28,
    conversion: "67.9%",
    barClassName: "bg-cyan-500",
  },
  {
    id: "enrolled",
    label: "Đã nhập học",
    value: "1,026",
    percentage: 22,
    conversion: "69.2%",
    barClassName: "bg-green-500",
  },
];

export const attentionItems: AttentionItem[] = [
  {
    id: "sla-breached",
    label: "SLA đã vi phạm",
    description: "Cần trưởng nhóm xử lý và ghi nhận lý do",
    count: "24 hồ sơ",
    priority: "high",
    tone: "danger",
    href: "/director/sla",
  },
  {
    id: "unassigned",
    label: "Chưa phân công",
    description: "Đang chờ phân công theo cơ sở và ngành",
    count: "68 hồ sơ",
    priority: "high",
    tone: "warning",
    href: "/director/student-pool",
  },
  {
    id: "intake-review",
    label: "Hồ sơ chờ rà soát",
    description: "Nghi vấn trùng danh tính hoặc thiếu dữ liệu",
    count: "17 hồ sơ",
    priority: "medium",
    tone: "info",
    href: "/director/intake-review",
  },
  {
    id: "conversion",
    label: "Chờ đối soát chuyển đổi",
    description: "Hồ sơ đã nhập học chưa liên kết hoàn tất",
    count: "9 hồ sơ",
    priority: "medium",
    tone: "primary",
    href: "/director/enrollment/reconciliation",
  },
  {
    id: "approvals",
    label: "Phê duyệt đang chờ",
    description: "Thay đổi danh mục học thuật và chính sách",
    count: "7 yêu cầu",
    priority: "low",
    tone: "success",
    href: "/director/governance/approvals",
  },
];

export const teamPerformance: TeamPerformance[] = [
  {
    id: "hanoi-tech",
    name: "Hà Nội · Khối Công nghệ",
    campus: "HN",
    activeLeads: "2,846",
    sla: "96.4%",
    enrolled: "286",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "hcm-business",
    name: "TP.HCM · Khối Kinh tế",
    campus: "HCM",
    activeLeads: "2,418",
    sla: "94.1%",
    enrolled: "241",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "danang-language",
    name: "Đà Nẵng · Khối Ngôn ngữ",
    campus: "ĐN",
    activeLeads: "1,764",
    sla: "91.8%",
    enrolled: "176",
    conversion: "10.0%",
    trend: "up",
  },
  {
    id: "hotline-national",
    name: "Hotline toàn quốc",
    campus: "ALL",
    activeLeads: "3,112",
    sla: "88.6%",
    enrolled: "155",
    conversion: "5.0%",
    trend: "down",
  },
];

export const sourcePerformance: SourcePerformance[] = [
  {
    id: "facebook",
    label: "Quảng cáo Facebook",
    leads: "3,920",
    applicants: "684",
    enrolled: "318",
    share: 31,
    barClassName: "bg-brand-500",
  },
  {
    id: "school-tour",
    label: "Tư vấn tại trường",
    leads: "2,486",
    applicants: "524",
    enrolled: "286",
    share: 24,
    barClassName: "bg-orange-400",
  },
  {
    id: "zalo",
    label: "Zalo OA",
    leads: "2,138",
    applicants: "418",
    enrolled: "224",
    share: 19,
    barClassName: "bg-cyan-500",
  },
  {
    id: "website",
    label: "Website / Biểu mẫu",
    leads: "1,842",
    applicants: "326",
    enrolled: "121",
    share: 14,
    barClassName: "bg-purple-400",
  },
  {
    id: "open-day",
    label: "Ngày hội tuyển sinh",
    leads: "1,026",
    applicants: "232",
    enrolled: "77",
    share: 8,
    barClassName: "bg-green-500",
  },
];
