"use client";

import { useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, Tooltip, XAxis, YAxis } from "recharts";

import { Card, CardHeader, CardTitle } from "@/components/tailgrids/core/card";
import { ChartContainer } from "@/components/tailgrids/core/chart";
import { funnelData, capabilityRows, priorityActions, regions, trendData } from "./data";
import RegionalPerformanceHeader from "./regional-performance-header";
import type { HealthTone, RegionPerformance } from "./types";

const toneClass: Record<HealthTone, string> = { good: "bg-success-500", watch: "bg-warning-500", critical: "bg-error-500" };
const toneLabel: Record<HealthTone, string> = { good: "Tốt", watch: "Cần theo dõi", critical: "Cần can thiệp" };

export default function RegionalPerformanceDashboard() {
  const [selected, setSelected] = useState("central");
  const selectedRegion = useMemo(() => regions.find((region) => region.id === selected) ?? regions[1], [selected]);
  return <main className="min-w-0 space-y-5 overflow-hidden px-2 py-4 pb-8 lg:px-6"><RegionalPerformanceHeader /><div className="space-y-5"><Scorecards selected={selected} onSelect={setSelected} /><PerformancePulse region={selectedRegion} /><div className="grid min-w-0 grid-cols-1 gap-5 lg:grid-cols-2"><EnrollmentTrend region={selectedRegion} /><FunnelAnalysis region={selectedRegion} /></div><CapabilityMatrix /><PriorityActions region={selectedRegion} /><RegionalTable selected={selectedRegion} /></div></main>;
}

function Scorecards({ selected, onSelect }: { selected: string; onSelect: (id: string) => void }) { return <section aria-label="Tóm tắt kết quả theo khu vực" className="grid grid-cols-1 gap-4 lg:grid-cols-3">{regions.map((region) => <button key={region.id} type="button" aria-pressed={selected === region.id} onClick={() => onSelect(region.id)} className={`rounded-xl border p-5 text-left transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500 ${selected === region.id ? "border-primary-500 bg-primary-50/30" : "border-card-border bg-card-background hover:border-primary-300"}`}><div className="flex items-center justify-between"><span className="font-semibold text-text-primary">{region.name}</span><span className="inline-flex items-center gap-1.5 text-xs text-text-secondary"><i className={`size-2 rounded-full ${toneClass[region.health]}`} />{toneLabel[region.health]}</span></div><div className="mt-4 grid grid-cols-2 gap-4"><Metric label="Hồ sơ đăng ký" value={region.applications.toLocaleString("vi-VN")} change={region.applicationChange} /><Metric label="Nhập học" value={region.enrollments.toLocaleString("vi-VN")} change={region.enrollmentChange} /></div><div className="mt-4 grid grid-cols-3 border-y border-card-border py-3 text-xs"><span className="text-text-tertiary">Tỷ lệ nhập học<strong className="mt-1 block text-sm text-text-primary">{region.conversion}%</strong></span><span className="text-text-tertiary">Tư vấn viên<strong className="mt-1 block text-sm text-text-primary">{region.activeAdvisors}</strong></span><span className="text-text-tertiary">Độ bận đội ngũ<strong className={`mt-1 block text-sm ${region.capacity > 90 ? "text-error-500" : "text-text-primary"}`}>{region.capacity}%</strong></span></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-text-tertiary">Đạt chỉ tiêu</span><span className="font-semibold text-text-primary">{region.targetAchievement}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-background-soft-100"><div className="h-full rounded-full bg-primary-500" style={{ width: `${region.targetAchievement}%` }} /></div></button>)}</section>; }
function Metric({ label, value, change }: { label: string; value: string; change: number }) { const up = change >= 0; return <div><p className="text-xs text-text-tertiary">{label}</p><p className="mt-1 text-xl font-semibold text-text-primary">{value}</p><p className={`mt-1 text-xs font-medium ${up ? "text-success-500" : "text-error-500"}`}>{up ? "↑" : "↓"} {Math.abs(change)}% so với kỳ trước</p></div>; }
function PerformancePulse({ region: selectedRegion }: { region: RegionPerformance }) { return <section className="grid grid-cols-1 gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Card className="p-5"><CardHeader className="mb-4"><div><CardTitle>Kết quả theo khu vực</CardTitle><p className="mt-1 text-xs text-text-tertiary">So sánh mức đạt chỉ tiêu và tỷ lệ hồ sơ chuyển thành nhập học.</p></div></CardHeader><div className="space-y-4">{regions.map((region) => <div key={region.id} className={`rounded-lg px-3 py-3 ${region.id === selectedRegion.id ? "bg-badge-primary-background" : "bg-background-soft-50"}`}><div className="flex items-center justify-between gap-3"><span className={`text-sm font-medium ${region.id === selectedRegion.id ? "text-primary-500" : "text-text-primary"}`}>{region.name}</span><span className="text-xs text-text-tertiary">{toneLabel[region.health]}</span></div><div className="mt-3 grid grid-cols-2 gap-4"><ProgressMetric label="Đạt chỉ tiêu" value={region.targetAchievement} display={`${region.targetAchievement}%`} tone={region.targetAchievement >= 85 ? "success" : "warning"} /><ProgressMetric label="Tỷ lệ nhập học" value={region.conversion} display={`${region.conversion}%`} max={30} tone={region.conversion >= 22 ? "success" : "warning"} /></div></div>)}</div></Card><Card className="p-5"><CardHeader className="mb-4"><div><CardTitle>Mức độ bận của đội ngũ</CardTitle><p className="mt-1 text-xs text-text-tertiary">Tỷ lệ khả năng xử lý hồ sơ đã sử dụng. Trên 90% cần hỗ trợ.</p></div></CardHeader><div className="space-y-4">{regions.map((region) => <div key={region.id}><div className="flex items-center justify-between gap-3 text-xs"><span className={`font-medium ${region.id === selectedRegion.id ? "text-primary-500" : "text-text-secondary"}`}>{region.name}</span><span className="font-semibold text-text-primary">{region.capacity}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-background-soft-100"><div className={`h-full rounded-full ${region.capacity > 90 ? "bg-error-500" : region.capacity > 80 ? "bg-warning-500" : "bg-success-500"}`} style={{ width: `${region.capacity}%` }} /></div><p className="mt-1 text-xs text-text-tertiary">{region.activeAdvisors} tư vấn viên đang hoạt động</p></div>)}</div></Card></section>; }
function ProgressMetric({ label, value, display, max = 100, tone }: { label: string; value: number; display: string; max?: number; tone: "success" | "warning" }) { const width = Math.min(100, (value / max) * 100); return <div><div className="flex items-center justify-between gap-2 text-xs"><span className="text-text-tertiary">{label}</span><span className={`font-semibold ${tone === "success" ? "text-success-500" : "text-warning-500"}`}>{display}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-background-soft-100"><div className={`h-full rounded-full ${tone === "success" ? "bg-success-500" : "bg-warning-500"}`} style={{ width: `${width}%` }} /></div></div>; }
function EnrollmentTrend({ region }: { region: RegionPerformance }) { const ratio = region.applications / 2134; const data = trendData.map((item) => ({ ...item, applications: Math.round(item.applications * ratio), enrollments: Math.round(item.enrollments * (region.enrollments / 482)), previousApplications: Math.round(item.previousApplications * ratio) })); return <ChartCard title={`Xu hướng ${region.name}`} description="Hồ sơ và nhập học 6 tháng, thay đổi theo vùng chọn"><LineChart data={data} margin={{ top: 8, right: 4, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--border-color-base-100)" strokeDasharray="4 4" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "var(--text-tertiary)", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--text-tertiary)", fontSize: 12 }} /><Tooltip content={<TooltipContent />} /><Line name="Hồ sơ kỳ này" type="monotone" dataKey="applications" stroke="var(--primary-500)" strokeWidth={2.5} dot={false} /><Line name="Hồ sơ kỳ trước" type="monotone" dataKey="previousApplications" stroke="var(--primary-300)" strokeWidth={2} strokeDasharray="5 5" dot={false} /><Line name="Nhập học" type="monotone" dataKey="enrollments" stroke="var(--success-500)" strokeWidth={2.5} dot={false} /></LineChart></ChartCard>; }
function FunnelAnalysis({ region }: { region: RegionPerformance }) { const key = region.id === "north" ? "north" : region.id === "central" ? "central" : "south"; const data = funnelData.map((item, index, rows) => ({ stage: item.stage, value: item[key], remaining: (item[key] / rows[0][key]) * 100, stepConversion: index === 0 ? 100 : (item[key] / rows[index - 1][key]) * 100 })); return <Card className="min-w-0 p-5"><CardHeader className="mb-4"><div><CardTitle>Số hồ sơ còn lại sau từng bước</CardTitle><p className="mt-1 text-xs text-text-tertiary">{region.name} · tỷ lệ tính từ tổng hồ sơ ban đầu.</p></div></CardHeader><div className="space-y-4">{data.map((item) => <div key={item.stage} className="grid grid-cols-[minmax(80px,0.7fr)_minmax(0,2fr)_auto] items-center gap-3"><span className="text-xs font-medium text-text-secondary">{item.stage}</span><div className="h-8 overflow-hidden rounded-md bg-background-soft-50"><div className="flex h-full min-w-20 items-center rounded-md bg-primary-500 px-3 text-xs font-semibold text-white" style={{ width: `${Math.max(18, item.remaining)}%` }}>{item.value.toLocaleString("vi-VN")}</div></div><div className="text-right"><p className="text-xs font-semibold text-text-primary">{item.remaining.toFixed(1).replace(".", ",")}%</p><p className="mt-0.5 text-[11px] text-text-tertiary">{item.stepConversion.toFixed(1).replace(".", ",")}% bước</p></div></div>)}</div></Card>; }
function CapabilityMatrix() { return <Card className="min-w-0 p-5"><CardHeader className="mb-4"><div><CardTitle>Khả năng đáp ứng theo vùng</CardTitle><p className="mt-1 text-xs text-text-tertiary">Mức độ đáp ứng ở từng khâu tuyển sinh.</p></div></CardHeader><div className="overflow-x-auto"><table className="w-full min-w-105 text-sm"><thead className="text-left text-xs text-text-tertiary"><tr><th className="pb-3 font-medium">Khâu tuyển sinh</th><th className="pb-3 text-center font-medium">Miền Bắc</th><th className="pb-3 text-center font-medium">Miền Trung</th><th className="pb-3 text-center font-medium">Miền Nam</th></tr></thead><tbody>{capabilityRows.map((row) => <tr key={row.label} className="border-t border-card-border"><td className="py-3 text-text-secondary">{row.label}</td>{([row.north,row.central,row.south] as HealthTone[]).map((tone, index) => <td key={index} className="py-3 text-center"><span className="inline-flex items-center gap-1.5 text-xs text-text-secondary"><i className={`size-2 rounded-full ${toneClass[tone]}`} />{toneLabel[tone]}</span></td>)}</tr>)}</tbody></table></div></Card>; }
function PriorityActions({ region }: { region: RegionPerformance }) { const actions = priorityActions.filter((action) => action.region === region.name || action.region === "Toàn bộ"); return <Card className="p-5"><CardHeader className="mb-4"><div><CardTitle>Việc cần làm</CardTitle><p className="mt-1 text-xs text-text-tertiary">{region.name} · sắp theo mức độ ưu tiên.</p></div></CardHeader><ol className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{actions.map((action) => <li key={action.id} className="rounded-lg bg-background-soft-50 p-4"><div><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-text-primary">{action.title}</p><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-medium ${action.tone === "critical" ? "bg-badge-error-background text-badge-error-text" : action.tone === "watch" ? "bg-badge-warning-background text-badge-warning-text" : "bg-badge-success-background text-badge-success-text"}`}>{action.priority}</span></div><p className="mt-2 text-xs leading-5 text-text-tertiary">{action.detail}</p></div></li>)}{actions.length === 0 && <li className="py-6 text-sm text-text-secondary">Chưa có việc cần xử lý gấp ở vùng này.</li>}</ol></Card>; }
function RegionalTable({ selected }: { selected: RegionPerformance }) { return <Card className="overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><CardTitle>So sánh nhanh các vùng</CardTitle><p className="mt-1 text-xs text-text-tertiary">Vùng đang xem: {selected.name}</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-190 text-sm"><thead className="bg-background-soft-50 text-left text-xs text-text-tertiary"><tr>{["Khu vực","Hồ sơ","Nhập học","Tỷ lệ nhập học","Đạt chỉ tiêu","Tư vấn viên","Độ bận đội ngũ"].map((head) => <th key={head} className="px-5 py-3 font-medium">{head}</th>)}</tr></thead><tbody>{regions.map((region) => <tr key={region.id} className="border-t border-card-border"><td className="px-5 py-4 font-medium text-text-primary">{region.name}</td><td className="px-5 py-4 text-text-secondary">{region.applications.toLocaleString("vi-VN")}</td><td className="px-5 py-4 text-text-secondary">{region.enrollments.toLocaleString("vi-VN")}</td><td className="px-5 py-4 text-text-secondary">{region.conversion}%</td><td className="px-5 py-4 text-text-secondary">{region.targetAchievement}%</td><td className="px-5 py-4 text-text-secondary">{region.activeAdvisors}</td><td className="px-5 py-4"><span className={region.capacity > 90 ? "font-medium text-error-500" : region.capacity > 80 ? "font-medium text-warning-500" : "text-text-secondary"}>{region.capacity}%</span></td></tr>)}</tbody></table></div></Card>; }
function ChartCard({ title, description, children }: { title: string; description: string; children: React.ReactElement }) { return <Card className="min-w-0 p-5"><CardHeader className="mb-4"><div><CardTitle>{title}</CardTitle><p className="mt-1 text-xs text-text-tertiary">{description}</p></div></CardHeader><div className="h-68 min-h-68 w-full"><ChartContainer width="100%" height="100%" minWidth={0} minHeight={0}>{children}</ChartContainer></div></Card>; }
function TooltipContent({ active, payload, label }: { active?: boolean; payload?: { name?: string; value?: number; color?: string }[]; label?: string }) { if (!active || !payload?.length) return null; return <div className="rounded-lg border border-card-border bg-card-background p-3 text-xs shadow-sm"><p className="mb-2 font-semibold text-text-primary">{label}</p>{payload.map((item) => <p key={item.name} className="flex justify-between gap-5 py-0.5 text-text-secondary"><span>{item.name}</span><strong className="text-text-primary">{item.value?.toLocaleString("vi-VN")}</strong></p>)}</div>; }
