import type {
  StudentCallRecord,
  StudentTaskItem,
  StudentZaloMessage,
} from "@/services/api/students/types";

const mockAssignee = "Trần Quốc Bảo";

export const touchpoints = [
  { date: "06/06 · 16:42", channel: "Cuộc gọi", title: "Tư vấn lần 2", detail: "Xác nhận ngành phù hợp; phụ huynh còn hỏi về chi phí.", tone: "success" as const },
  { date: "04/06 · 20:18", channel: "Zalo", title: "Phụ huynh hỏi học bổng", detail: "Đã gửi chính sách học bổng và hẹn gọi lại.", tone: "primary" as const },
  { date: "02/06 · 09:30", channel: "Sự kiện", title: "Check-in Open Day", detail: "Tham gia phiên chuyên ngành AI và hỏi về đầu ra.", tone: "success" as const },
  { date: "30/05 · 22:11", channel: "Website", title: "Xem trang học phí", detail: "Xem bảng phí 3 lần trong cùng một phiên truy cập.", tone: "warning" as const },
  { date: "28/05 · 14:05", channel: "Sự kiện", title: "Career Talk", detail: "Đăng ký nhận tư vấn và để lại nguyện vọng ngành AI.", tone: "primary" as const },
];

export const documents = [
  { name: "Phiếu đăng ký tư vấn", type: "Biểu mẫu trực tuyến", status: "Đã xác nhận", tone: "success" as const, date: "28/05/2026" },
  { name: "Bảng điểm lớp 11", type: "Tài liệu học tập", status: "Đã nhận", tone: "success" as const, date: "02/06/2026" },
  { name: "Chứng chỉ tiếng Anh", type: "Tài liệu học tập", status: "Chờ bổ sung", tone: "warning" as const, date: "Còn thiếu" },
  { name: "CCCD / giấy tờ tùy thân", type: "Hồ sơ nhập học", status: "Chưa bắt đầu", tone: "gray" as const, date: "—" },
  { name: "Minh chứng đối tượng học bổng", type: "Học bổng", status: "Chưa bắt đầu", tone: "gray" as const, date: "—" },
];

export const tasks: StudentTaskItem[] = [
  { id: "task-1", title: "Gọi xác nhận học phí với phụ huynh", assignee: mockAssignee, dueDate: "10/06/2026", dueTime: "16:00", taskType: "call", status: "todo", priority: "Cao", notes: "Gọi vào buổi chiều, hỏi thêm về học bổng theo học kỳ." },
  { id: "task-2", title: "Gửi hồ sơ học bổng bổ sung", assignee: mockAssignee, dueDate: "08/06/2026", dueTime: "09:00", taskType: "email", status: "in-progress", priority: "Trung bình" },
  { id: "task-3", title: "Nhắc nộp chứng chỉ tiếng Anh", assignee: mockAssignee, dueDate: "05/06/2026", dueTime: "10:30", taskType: "todo", status: "done", priority: "Thấp" },
];
export const zaloMessages: StudentZaloMessage[] = [
  {
    id: "zalo-1",
    time: "06/06/2026 · 16:42",
    senderName: "Nguyễn Văn Minh",
    senderRole: "Bố của học sinh",
    recipientName: mockAssignee,
    recipientRole: "Tư vấn viên",
    content: "Em gửi giúp anh bảng học phí theo từng học kỳ và điều kiện nhận học bổng 30% nhé.",
    direction: "inbound",
    status: "read",
    conversationTitle: "Hỏi học phí & học bổng",
  },
  {
    id: "zalo-2",
    time: "06/06/2026 · 16:49",
    senderName: mockAssignee,
    senderRole: "Tư vấn viên",
    recipientName: "Nguyễn Văn Minh",
    recipientRole: "Bố của học sinh",
    content: "Dạ được anh. Em gửi bảng phí và thông tin học bổng trong tin nhắn tiếp theo, sau đó mình trao đổi thêm qua cuộc gọi lúc 17:00 nhé.",
    direction: "outbound",
    status: "delivered",
    conversationTitle: "Hỏi học phí & học bổng",
    attachmentName: "Bang-hoc-phi-2026.pdf",
  },
  {
    id: "zalo-3",
    time: "04/06/2026 · 20:18",
    senderName: "Nguyễn Minh An",
    senderRole: "Học sinh",
    recipientName: mockAssignee,
    recipientRole: "Tư vấn viên",
    content: "Em muốn hỏi thêm về các dự án thực tế của ngành Trí tuệ nhân tạo và cơ hội thực tập ạ.",
    direction: "inbound",
    status: "read",
    conversationTitle: "Tìm hiểu ngành học",
  },
];

export const calls: StudentCallRecord[] = [
  {
    id: "1788095122.629019",
    time: "2026-08-30T20:05:22+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 19,
    topic: "Inbound C0449 · 1788095122.629019",
    summary: "Không nghe máy · tổng thời lượng 00:19 · nguồn Worldfone.",
  },
  {
    id: "1788088431.627663",
    time: "2026-08-30T18:13:51+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 124,
    topic: "Inbound C0449 · 1788088431.627663",
    summary: "Không nghe máy · tổng thời lượng 02:04 · nguồn Worldfone.",
  },
  {
    id: "1788086727.627182",
    time: "2026-08-30T17:45:27+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 12,
    topic: "Inbound C0449 · 1788086727.627182",
    summary: "Không nghe máy · tổng thời lượng 00:12 · nguồn Worldfone.",
  },
  {
    id: "1788085260.626678",
    time: "2026-08-30T17:21:00+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 59,
    topic: "Inbound C0449 · 1788085260.626678",
    summary: "Không nghe máy · tổng thời lượng 00:59 · nguồn Worldfone.",
  },
  {
    id: "1788084299.626492",
    time: "2026-08-30T17:04:59+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 16,
    topic: "Inbound C0449 · 1788084299.626492",
    summary: "Không nghe máy · tổng thời lượng 00:16 · nguồn Worldfone.",
  },
  {
    id: "1788083167.626270",
    time: "2026-08-30T16:46:07+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 20,
    topic: "Inbound C0449 · 1788083167.626270",
    summary: "Không nghe máy · tổng thời lượng 00:20 · nguồn Worldfone.",
  },
  {
    id: "1788082739.626189",
    time: "2026-08-30T16:38:59+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 27,
    topic: "Inbound C0449 · 1788082739.626189",
    summary: "Không nghe máy · tổng thời lượng 00:27 · nguồn Worldfone.",
  },
  {
    id: "1788081890.626069",
    time: "2026-08-30T16:24:50+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 20,
    topic: "Inbound C0449 · 1788081890.626069",
    summary: "Không nghe máy · tổng thời lượng 00:20 · nguồn Worldfone.",
  },
  {
    id: "1788081819.626054",
    time: "2026-08-30T16:23:39+07:00",
    direction: "inbound",
    outcome: "no-answer",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 39,
    topic: "Inbound C0449 · 1788081819.626054",
    summary: "Không nghe máy · tổng thời lượng 00:39 · nguồn Worldfone.",
  },
  {
    id: "1788081658.626026",
    time: "2026-08-30T16:20:58+07:00",
    direction: "inbound",
    outcome: "connected",
    callerName: "Khách inbound",
    callerRole: "Khách hàng",
    receiverName: "Tư vấn viên",
    receiverRole: "Tổng đài viên",
    durationSeconds: 28,
    topic: "Inbound C0449 · 1788081658.626026",
    summary: "Đã kết nối · đàm thoại 00:28 · nguồn Worldfone.",
  },
];

export const localDemoCallsEnabled = process.env.NEXT_PUBLIC_ENABLE_DEMO_CALLS === "true";

export function resolveStudentCalls(value?: StudentCallRecord[]): StudentCallRecord[] {
  return value ?? (localDemoCallsEnabled ? calls : []);
}
