import { CheckCircle1, Envelope1, MapMarker5, Phone } from "@tailgrids/icons";

import { Badge } from "@/components/tailgrids/core/badge";
import { Card, CardHeader, CardTitle } from "@/components/tailgrids/core/card";

import type { Student360SectionProps } from "./types";

export default function StudentDetailsTab({ data }: Student360SectionProps) {
  const { student } = data;

  return <div className="grid items-stretch gap-5 lg:grid-cols-2"><Card className="h-full p-5"><CardHeader className="mb-5"><CardTitle>Thông tin cá nhân</CardTitle><Badge color="success"><CheckCircle1 size={13} />Đã xác thực</Badge></CardHeader><div><dl className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><div><dt className="text-xs text-text-tertiary">Họ và tên</dt><dd className="mt-1 text-sm font-medium text-text-primary">{student.name}</dd></div><div><dt className="text-xs text-text-tertiary">Mã hồ sơ</dt><dd className="mt-1 text-sm font-medium text-text-primary">{student.code}</dd></div><div><dt className="text-xs text-text-tertiary">Ngày sinh</dt><dd className="mt-1 text-sm font-medium text-text-primary">20/07/2007</dd></div><div><dt className="text-xs text-text-tertiary">Giới tính</dt><dd className="mt-1 text-sm font-medium text-text-primary">Nữ</dd></div><div className="sm:col-span-2"><dt className="text-xs text-text-tertiary">Trường THPT</dt><dd className="mt-1 flex items-start gap-1.5 text-sm font-medium text-text-primary"><MapMarker5 size={15} className="mt-0.5 text-icon-tertiary" />{student.school}</dd></div><div><dt className="text-xs text-text-tertiary">Số điện thoại</dt><dd className="mt-1 flex items-center gap-1.5 text-sm font-medium text-text-primary"><Phone size={14} className="text-icon-tertiary" />{student.phone}</dd></div><div><dt className="text-xs text-text-tertiary">Email</dt><dd className="mt-1 flex items-center gap-1.5 text-sm font-medium text-text-primary"><Envelope1 size={14} className="text-icon-tertiary" />{student.email}</dd></div></dl><div className="mt-5 flex items-center justify-between gap-3 rounded-xl bg-badge-success-background p-3"><p className="text-xs font-medium text-badge-success-text">Đã đồng ý nhận tư vấn qua điện thoại và Zalo.</p><Badge color="success">Đã đồng ý</Badge></div></div></Card><Card className="h-full border-info-500/20 p-5"><CardHeader className="mb-5"><CardTitle>Học tập & định hướng</CardTitle><Badge color="sky">Phù hợp cao</Badge></CardHeader><dl className="grid gap-x-6 gap-y-5 sm:grid-cols-2">{[...data.academics, { label: "Lớp hiện tại", value: student.grade }, { label: "Nguyện vọng ưu tiên", value: student.major }, { label: "Khu vực", value: student.province }, { label: "Cập nhật gần nhất", value: "06/06/2026 · 17:05" }].map((item) => <div key={item.label}><dt className="text-xs text-text-tertiary">{item.label}</dt><dd className="mt-1 text-sm font-medium text-text-primary">{item.value}</dd></div>)}</dl></Card></div>;
}
