import { Calendar, Phone } from "@tailgrids/icons";

import { Badge } from "@/components/tailgrids/core/badge";
import { Card, CardHeader, CardTitle } from "@/components/tailgrids/core/card";

import ParentProfileCard from "./parent-profile-card";
import type { Student360SectionProps } from "./types";

export default function StudentFamilyTab({ data }: Student360SectionProps) {
  return <div className="space-y-5"><div className="grid items-stretch gap-5 lg:grid-cols-2"><ParentProfileCard data={data} /><Card className="h-full p-5"><CardHeader className="mb-5"><div><CardTitle>Băn khoăn cần tháo gỡ</CardTitle><p className="mt-1 text-xs leading-5 text-text-tertiary">Các câu hỏi chưa được giải quyết hoàn toàn.</p></div><Badge color="warning">{data.parentProfile.concerns.length} nhóm quan tâm</Badge></CardHeader><div className="space-y-3"><div className="rounded-lg border border-warning-200 bg-badge-warning-background p-4"><p className="text-sm font-semibold text-badge-warning-text">{data.parentProfile.concerns[0]}</p><p className="mt-1 text-xs leading-5 text-text-secondary">Đây là rào cản ưu tiên cần được xử lý trong lần trao đổi tiếp theo.</p></div>{data.parentProfile.concerns.slice(1).map((concern) => <div key={concern} className="rounded-lg border border-card-border p-4"><p className="text-sm font-semibold text-text-primary">{concern}</p><p className="mt-1 text-xs leading-5 text-text-secondary">Cần chuẩn bị thông tin có dẫn chứng để phụ huynh đối chiếu trước khi quyết định.</p></div>)}</div></Card></div><Card className="p-5"><CardHeader className="mb-5"><div><CardTitle>Lịch sử trao đổi với gia đình</CardTitle><p className="mt-1 text-xs leading-5 text-text-tertiary">Các cuộc trao đổi có ảnh hưởng đến quyết định.</p></div></CardHeader><div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-card-border p-4"><Phone size={17} className="text-primary-500" /><p className="mt-3 text-sm font-semibold text-text-primary">Tư vấn lần 1</p><p className="mt-1 text-xs text-text-tertiary">31/05/2026 · 17:20</p><p className="mt-2 text-sm leading-5 text-text-secondary">Giới thiệu chương trình {data.student.major} và ghi nhận nhu cầu của gia đình.</p></div><div className="rounded-lg border border-card-border p-4"><Calendar size={17} className="text-primary-500" /><p className="mt-3 text-sm font-semibold text-text-primary">Trao đổi gần nhất</p><p className="mt-1 text-xs text-text-tertiary">{data.parentProfile.lastInteraction}</p><p className="mt-2 text-sm leading-5 text-text-secondary">Đã ghi nhận các mối quan tâm riêng và kênh liên hệ phù hợp.</p></div><div className="rounded-lg border border-primary-200 bg-badge-primary-background p-4"><Phone size={17} className="text-primary-500" /><p className="mt-3 text-sm font-semibold text-text-primary">Cuộc gọi đề xuất</p><p className="mt-1 text-xs text-text-tertiary">{data.parentProfile.bestContactTime}</p><p className="mt-2 text-sm leading-5 text-text-secondary">Trao đổi trực tiếp với {data.parentProfile.relation.toLowerCase()} để chốt bước hành động tiếp theo.</p></div></div></Card></div>;
}
