import { ArrowRight, ArrowUpward, InfoCircle } from "@tailgrids/icons";

import { Badge } from "@/components/tailgrids/core/badge";
import { Card, CardHeader, CardTitle } from "@/components/tailgrids/core/card";
import { funnelStages, regionOpportunities } from "./data";

export default function SegmentAnalysis() {
  return (
    <section className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,0.75fr)]">
      <Card className="min-w-0 p-0">
        <CardHeader className="border-b border-card-border p-5"><div><CardTitle>Phễu quy mô & chuyển đổi</CardTitle><p className="mt-1 text-xs leading-5 text-text-tertiary">Tệp nữ lớp 12 quan tâm AI tại Đồng Nai trong kỳ tuyển sinh 2026.</p></div><Badge color="primary">3.420 prospects</Badge></CardHeader>
        <div className="p-5">
          <div className="mb-3 grid grid-cols-[minmax(150px,1fr)_68px] gap-3 text-xs font-medium text-text-tertiary sm:grid-cols-[145px_minmax(200px,1fr)_68px_66px]"><span>Giai đoạn</span><span className="hidden sm:block">Quy mô</span><span className="text-right">Số lượng</span><span className="hidden text-right sm:block">Chuyển đổi</span></div>
          <div className="space-y-3.5">{funnelStages.map((stage, index) => <div key={stage.label} className="grid grid-cols-[minmax(150px,1fr)_68px] items-center gap-3 sm:grid-cols-[145px_minmax(200px,1fr)_68px_66px]"><span className="text-sm text-text-secondary">{stage.label}</span><div className="hidden h-3 overflow-hidden rounded-full bg-background-soft-200 sm:block"><div className={index === 0 ? "h-full rounded-full bg-primary-300" : "h-full rounded-full bg-primary-500"} style={{ width: `${stage.width}%` }} /></div><strong className="text-right text-sm text-text-primary">{stage.value}</strong><span className="hidden text-right text-xs text-success-500 sm:block">{stage.conversion ?? "—"}</span></div>)}</div>
          <p className="mt-5 border-t border-card-border pt-4 text-xs leading-5 text-text-tertiary">Tỷ lệ nộp hồ sơ cao hơn 1,5 điểm phần trăm so với tệp nữ lớp 12 quan tâm AI toàn quốc.</p>
        </div>
      </Card>
      <Card className="min-w-0 p-0"><CardHeader className="border-b border-card-border p-5"><div><CardTitle>Xếp hạng theo địa bàn</CardTitle><p className="mt-1 text-xs leading-5 text-text-tertiary">Chỉ số tiềm năng tổng hợp quy mô, tăng trưởng và chuyển đổi.</p></div><InfoCircle size={17} className="text-text-tertiary" aria-label="Thông tin về chỉ số tiềm năng" /></CardHeader><div className="p-3">{regionOpportunities.map((region) => <div key={region.name} className={`grid grid-cols-[24px_minmax(0,1fr)_94px_32px] items-center gap-3 rounded-lg px-2.5 py-3 ${region.selected ? "bg-badge-primary-background" : ""}`}><span className={region.selected ? "text-xs font-semibold text-badge-primary-text" : "text-xs text-text-tertiary"}>{region.rank}</span><span className={region.selected ? "truncate text-sm font-medium text-badge-primary-text" : "truncate text-sm text-text-secondary"}>{region.name}</span><div className="h-2 overflow-hidden rounded-full bg-background-soft-200"><div className={region.selected ? "h-full rounded-full bg-primary-500" : "h-full rounded-full bg-success-500"} style={{ width: `${region.score}%` }} /></div><strong className={region.selected ? "text-right text-sm text-badge-primary-text" : "text-right text-sm text-text-primary"}>{region.score}</strong></div>)}</div></Card>
      <Card className="xl:col-span-2 p-0"><CardHeader className="border-b border-card-border p-5"><div><div className="flex flex-wrap items-center gap-2"><CardTitle>Cơ hội mới nổi</CardTitle><Badge color="success"><ArrowUpward size={13} />31% MoM</Badge></div><p className="mt-1 text-xs leading-5 text-text-tertiary">Phát hiện tự động từ thay đổi nhu cầu, quy mô thị trường và mức độ khai thác hiện tại.</p></div></CardHeader><div className="grid gap-5 p-5 md:grid-cols-[minmax(0,1fr)_auto]"><div><p className="text-base font-semibold text-text-primary">Nữ sinh quan tâm AI tại Đồng Nai tăng nhanh, nhưng audience targeting mới bao phủ 3,2% tệp.</p><p className="mt-2 max-w-3xl text-sm leading-6 text-text-secondary">Nhu cầu tăng 31% so với tháng trước; tỷ lệ đủ điều kiện cao hơn mức trung bình của nhóm AI. Ưu tiên kiểm tra 12 trường có quy mô lớn trước khi điều chỉnh phân bổ nguồn lực.</p></div><a href="/director/market-intelligence" className="inline-flex h-9 items-center justify-center gap-1 self-end rounded-lg text-sm font-medium text-button-primary-outline-text hover:bg-button-primary-outline-hover-background hover:text-button-primary-outline-hover-text focus-visible:ring-4 focus-visible:ring-button-outline-focus-ring md:self-center"><span>Xem khu vực liên quan</span><ArrowRight size={16} /></a></div></Card>
    </section>
  );
}
