import type {
  AssignmentRecord,
  Candidate,
  StepId,
  WorkflowStep,
} from "./types";

export const automationPath: StepId[] = [
  "input",
  "validation",
  "classification",
  "matching",
  "assignment",
];

export const candidates: Candidate[] = [
  { id: "sale-1", name: "Nguyễn Minh Anh", initials: "MA", workload: 28 },
  { id: "sale-2", name: "Trần Ngọc Mai", initials: "NM", workload: 34 },
  { id: "sale-3", name: "Lê Hoàng Nam", initials: "HN", workload: 41 },
];

// A single, fixed sample cohort. All counters and filters derive from these records.
export const initialRecords: AssignmentRecord[] = [
  {
    id: "HS-001",
    name: "Nguyễn Minh An",
    initials: "MA",
    school: "THPT Châu Văn Liêm",
    region: "Cần Thơ",
    interest: "Công nghệ thông tin",
    source: "Website tuyển sinh",
    time: "09:42",
    status: "assigned",
    ownerId: "sale-1",
    score: 92,
    method: "automatic",
  },
  {
    id: "HS-002",
    name: "Trần Ngọc Ánh",
    initials: "NA",
    school: "THPT Nguyễn Việt Hồng",
    region: "Cần Thơ",
    interest: "Quản trị kinh doanh",
    source: "Ngày hội tư vấn",
    time: "09:39",
    status: "assigned",
    ownerId: "sale-2",
    score: 89,
    method: "automatic",
  },
  {
    id: "HS-003",
    name: "Phạm Minh Khang",
    initials: "MK",
    school: "THPT Trần Đại Nghĩa",
    region: "Vĩnh Long",
    interest: "Công nghệ thông tin",
    source: "Website tuyển sinh",
    time: "09:36",
    status: "no_match",
    method: "automatic",
  },
  {
    id: "HS-004",
    name: "Lê Gia Hân",
    initials: "GH",
    school: "THPT Bùi Hữu Nghĩa",
    region: "",
    interest: "Ngôn ngữ Anh",
    source: "Ngày hội tư vấn",
    time: "09:32",
    status: "missing_data",
    method: "automatic",
  },
  {
    id: "HS-005",
    name: "Võ Quốc Bảo",
    initials: "QB",
    school: "THPT Phan Văn Trị",
    region: "Cần Thơ",
    interest: "Công nghệ thông tin",
    source: "Website tuyển sinh",
    time: "09:28",
    status: "assigned",
    ownerId: "sale-1",
    score: 90,
    method: "automatic",
  },
  {
    id: "HS-006",
    name: "Đặng Bảo Ngọc",
    initials: "BN",
    school: "THPT Nguyễn Đình Chiểu",
    region: "Đồng Tháp",
    interest: "Kế toán",
    source: "Ngày hội tư vấn",
    time: "09:25",
    status: "no_match",
    method: "automatic",
  },
  {
    id: "HS-007",
    name: "Nguyễn Hoàng Phúc",
    initials: "HP",
    school: "THPT Châu Văn Liêm",
    region: "Cần Thơ",
    interest: "Công nghệ thông tin",
    source: "Website tuyển sinh",
    time: "09:21",
    status: "assigned",
    ownerId: "sale-3",
    score: 87,
    method: "automatic",
  },
  {
    id: "HS-008",
    name: "Trần Khánh Linh",
    initials: "KL",
    school: "THPT Nguyễn Việt Hồng",
    region: "Cần Thơ",
    interest: "Ngôn ngữ Anh",
    source: "Website tuyển sinh",
    time: "09:18",
    status: "assigned",
    ownerId: "sale-2",
    score: 91,
    method: "automatic",
  },
  {
    id: "HS-009",
    name: "Lê Tuấn Kiệt",
    initials: "TK",
    school: "THPT Bùi Hữu Nghĩa",
    region: "Cần Thơ",
    interest: "Quản trị kinh doanh",
    source: "Ngày hội tư vấn",
    time: "09:14",
    status: "assigned",
    ownerId: "sale-1",
    score: 88,
    method: "automatic",
  },
  {
    id: "HS-010",
    name: "Phạm Thanh Trúc",
    initials: "TT",
    school: "THPT Phan Văn Trị",
    region: "Cần Thơ",
    interest: "Kế toán",
    source: "Website tuyển sinh",
    time: "09:10",
    status: "assigned",
    ownerId: "sale-3",
    score: 85,
    method: "automatic",
  },
  {
    id: "HS-011",
    name: "Võ Minh Thư",
    initials: "MT",
    school: "THPT Châu Văn Liêm",
    region: "Cần Thơ",
    interest: "Ngôn ngữ Anh",
    source: "Ngày hội tư vấn",
    time: "09:06",
    status: "assigned",
    ownerId: "sale-2",
    score: 93,
    method: "automatic",
  },
  {
    id: "HS-012",
    name: "Đỗ Anh Quân",
    initials: "AQ",
    school: "THPT Nguyễn Việt Hồng",
    region: "Cần Thơ",
    interest: "Công nghệ thông tin",
    source: "Website tuyển sinh",
    time: "09:02",
    status: "assigned",
    ownerId: "sale-1",
    score: 90,
    method: "automatic",
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    id: "input",
    title: "Tiếp nhận học sinh",
    description: "Website · Ngày hội tư vấn",
    detail: "Tiếp nhận thông tin học sinh mới từ các nguồn tuyển sinh của đội.",
    rules: [
      "Mỗi học sinh được ghi nhận một lần.",
      "Lưu nguồn tuyển sinh và thời điểm tiếp nhận.",
    ],
    tone: "blue",
    position: { x: 0, y: 0 },
  },
  {
    id: "validation",
    title: "Kiểm tra thông tin",
    description: "Đủ thông tin để phân công",
    detail:
      "Kiểm tra thông tin liên hệ, khu vực và bản ghi trùng trước khi tìm người phụ trách.",
    rules: [
      "Có thông tin liên hệ hợp lệ.",
      "Có khu vực để xác định người phụ trách.",
      "Thiếu thông tin hoặc nghi trùng: chuyển sang cần xử lý.",
    ],
    tone: "neutral",
    position: { x: 310, y: 0 },
  },
  {
    id: "classification",
    title: "Phân nhóm học sinh",
    description: "Khu vực · Ngành quan tâm",
    detail:
      "Xác định nhóm học sinh để tìm nhân sự có phạm vi phụ trách phù hợp.",
    rules: [
      "Nhóm theo khu vực và ngành quan tâm.",
      "Chưa biết ngành: sử dụng nhóm tư vấn chung.",
    ],
    tone: "blue",
    position: { x: 620, y: 0 },
  },
  {
    id: "matching",
    title: "Tìm người phù hợp",
    description: "Phạm vi phụ trách · Khối lượng",
    detail:
      "So sánh những nhân sự đủ điều kiện nhận học sinh, sau đó chọn người phù hợp nhất.",
    rules: [
      "Đang nhận học sinh và còn khả năng tiếp nhận.",
      "Ưu tiên khu vực, nhóm ngành phù hợp.",
      "Điểm phù hợp tối thiểu trong bản thử: 70/100.",
      "Không có người phù hợp: chuyển trưởng nhóm xử lý.",
    ],
    tone: "primary",
    position: { x: 310, y: 195 },
  },
  {
    id: "review",
    title: "Cần trưởng nhóm xử lý",
    description: "Thiếu thông tin / chưa phù hợp",
    detail:
      "Các học sinh chưa thể tự động phân công được giữ lại để trưởng nhóm kiểm tra.",
    rules: [
      "Bổ sung thông tin trước khi phân công.",
      "Có thể chọn người phụ trách và ghi rõ lý do.",
      "Không tự thay đổi người đã được phân công.",
    ],
    tone: "warning",
    position: { x: 0, y: 195 },
  },
  {
    id: "assignment",
    title: "Phân công phụ trách",
    description: "Ghi nhận người tiếp nhận",
    detail:
      "Ghi nhận người phụ trách, thời điểm và lý do phân công cho từng học sinh.",
    rules: [
      "Mỗi học sinh có một người phụ trách chính.",
      "Lưu rõ phân công tự động hay do trưởng nhóm chọn.",
    ],
    tone: "success",
    position: { x: 310, y: 390 },
  },
];
